# Generated by Django 4.2.8 on 2024-02-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
