# Generated by Django 4.2.8 on 2024-01-20 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('slug', models.CharField(blank=True, max_length=250, null=True, verbose_name='slug')),
                ('body', models.TextField(verbose_name='содержимое')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='превью')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('status', models.BooleanField(default=True, verbose_name='опубликован')),
                ('view_count', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ['-publish'],
            },
        ),
    ]
