# Generated by Django 4.2.8 on 2024-01-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
