# Generated by Django 4.2.8 on 2024-01-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_publish'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='date_publish',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='date_updated',
        ),
    ]
