# Generated by Django 4.2.8 on 2024-01-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'category', 'price', 'created_at', 'updated_at', 'is_active'), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_add',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_update',
            new_name='updated_at',
        ),
    ]
