# Generated by Django 4.2.8 on 2024-02-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_version', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default='1', verbose_name='номер версии')),
                ('name_version', models.CharField(choices=[('текущий', 'текущий'), ('новинка', 'новинка'), ('распродажа', 'распродажа'), ('скидка', 'скидка'), ('витрина', 'витрина'), ('уценённый', 'уценённый')], default='текущий', max_length=10, verbose_name='название версии')),
                ('is_active', models.BooleanField(default=False, verbose_name='текущая версия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт')),
            ],
        ),
    ]
