# Generated by Django 4.2.8 on 2024-02-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('product', 'num_version', 'name_version', 'is_active'), 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
    ]
