# Generated by Django 4.2.8 on 2024-02-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активная'),
        ),
        migrations.AlterField(
            model_name='version',
            name='name_version',
            field=models.CharField(choices=[('текущий', 'текущий'), ('новинка', 'новинка'), ('распродажа', 'распродажа'), ('скидка', 'скидка'), ('витрина', 'витрина'), ('уценённый', 'уценённый')], default='текущий', max_length=10, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='version',
            name='num_version',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default='1', verbose_name='номер'),
        ),
    ]
